; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=PyTodo
AppVersion=1.0
DefaultDirName={pf}\PyTodo
DefaultGroupName=PyTodo
OutputDir=.
OutputBaseFilename=PyTodoInstaller
Compression=lzma
SolidCompression=yes

[Files]
Source: "dist\pytodo.exe"; DestDir: "{app}"

[Icons]
Name: "{group}\PyTodo"; Filename: "{app}\pytodo.exe"
Name: "{commondesktop}\PyTodo"; Filename: "{app}\pytodo.exe"

[Tasks]
Name: "startup"; Description: "Run PyTodo at Windows Startup"; GroupDescription: "Additional Tasks:";

[Icons]
Name: "{userstartup}\PyTodo"; Filename: "{app}\pytodo.exe"; Tasks: startup
